export const RIGHTCONTAINERLAYOUTS = {
    SEARCHMESSAGE : 'SEARCHMESSAGE',
    USERPROFILE: 'USERPROFILE'
}

export const LEFTCONTAINERLAYOUTS = {
    RECENTCHATS : 'RECENTCHATS',
    PROFILEVIEW: 'PROFILEVIEW'
}